[pytest]
markers =
   negative_reg: негативные тест-кейсы регистрация
   negative_auth: негативные тест-кейсы авторизация
   positive_reg: позитивные тест-кейсы регистрация
   positive_auth: позитивные авторизации